'use server';

import nodemailer from 'nodemailer';
import { z } from 'zod';

const emailSchema = z.object({
  to: z.string().email(),
  username: z.string(),
  password: z.string(),
  date: z.string(),
});

type EmailPayload = z.infer<typeof emailSchema>;

export async function sendPasswordByEmail(payload: EmailPayload) {
  const result = emailSchema.safeParse(payload);

  if (!result.success) {
    return { success: false, error: 'Invalid input.' };
  }

  const { to, username, password, date } = result.data;

  // For Elastic Email, both 'user' and 'pass' are the API Key.
  const transporter = nodemailer.createTransport({
    host: process.env.EMAIL_SERVER_HOST,
    port: Number(process.env.EMAIL_SERVER_PORT),
    secure: Number(process.env.EMAIL_SERVER_PORT) === 465,
    auth: {
      user: process.env.ELASTIC_EMAIL_API_KEY,
      pass: process.env.ELASTIC_EMAIL_API_KEY,
    },
  });

  const emailHtml = `
    <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
      <h2 style="color: #3F51B5;">Your Password Details</h2>
      <p>Here are the details for your generated password:</p>
      <ul style="list-style-type: none; padding: 0;">
        <li style="margin-bottom: 10px;"><strong>Username/Application:</strong> ${username}</li>
        <li style="margin-bottom: 10px;"><strong>Password:</strong> <code style="background: #f4f4f4; padding: 2px 5px; border-radius: 4px;">${password}</code></li>
        <li style="margin-bottom: 10px;"><strong>Date Generated:</strong> ${new Date(date).toLocaleString()}</li>
      </ul>
      <p style="font-size: 0.9em; color: #777;">Generated by PassGenius.</p>
    </div>
  `;

  try {
    // Verify connection configuration
    await transporter.verify();

    const info = await transporter.sendMail({
      from: `PassGenius <${process.env.EMAIL_FROM}>`,
      to: to,
      subject: `Your generated password for ${username}`,
      html: emailHtml,
    });
    
    console.log("Message sent: %s", info.messageId);
    if (process.env.EMAIL_SERVER_HOST?.includes('ethereal.email')) {
      console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
    }

    return { success: true };
  } catch (error) {
    console.error('Full error object:', JSON.stringify(error, null, 2));
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
    return { success: false, error: `Failed to send email. Server log: ${errorMessage}` };
  }
}
